### PR TITLE
Recursive deep filtering

### PR DESCRIPTION
**Pull request by Ruben-Smit**
Hi! 
I've noticed the stats page is still too big for nightbot because I can't include things more specifically. I've changed your function so you can further deepen your search (instead of searching multiple things).
I've tested the actual javascript with jsfiddle but I haven't tested it with node.js. Doesn't do anything crazy though so it should be good.
You could also add it as a seperate function or not at all, it's not too necessary to have (for me) but I'd like to be able to do it.

Kind regards,

Ruben
(and thanks again for your awesome API)

### CODE REVIEW

**Comment by alfg** [comment]
Hi @Rerbun, 

I'm not sure this approach will work since the response outputted is no longer valid json, but just the text value of the filtered response. I think what you're looking for is a feature to compile a template or output another format (text).

The template approach would usually be implemented on the client consuming the api. How are you calling this api? Is it through nightbot's `urlfetch`?

**Comment by Ruben-Smit** [comment]
Oh yes you're right, I guess I didn't realize that. I'm sorry. 
Json output is fine (nightbot can parse it), I think I just didn't realize it would return the actual output instead of an object containing the output.

I guess the only problem was that "?include=stats"'s output on the stats page was still way too big to use. 

Yes I'm using nightbot's urlfetch. I think it would be quite a bit of work to get this to work with just text though so I guess I should fix this small piece of code first and make it work like (I) intended. I don't want to be a burden. :)

**Comment by alfg** [comment]
Hey, no worries! I'm glad you're helping me with this. :)

I was thinking we could add your utility update, but with an extra query param `format=text` to output in text format with the first `include` value only. This way we can support both json and plain text responses.

So for example:
`http://localhost:3000/stats/pc/us/Alf-1608?include=level&format=text`

This would output just the level value `437` in plain text for this case. This would be text friendly for nightbot, but I'm still unsure how to handle rendering the larger objects such as stats.

**Comment by Ruben-Smit** [comment]
That's a good idea.  :) I will try that. That would make it easier to use with nightbot. I guess I could just add the "format" parameter on the stats and profile page and check if it is text in my function. 

Larger objects are still fine to output in json. Nightbot can run javascript code which includes JSON.parse().

**Comment by Ruben-Smit** [comment]
I've changed my commit, it should always return a valid object now.
I couldn't get the api to run on my own pc (can't access the 0.0.0.0 IP it gives me) but it should be good.

I can add the text format feature later if you'd like, this would be enough to solve my problem though for now.

**Comment by alfg** [comment]
Hi @Rerbun, 

Can you post an example call you're using to meet your use case? 

Also, I think you can't use 0.0.0.0 cause of a bug with srv. It should work with localhost:3000 instead.

**Comment by Ruben-Smit** [comment]
Hi!,

localhost:3000 worked! (I guess that was pretty stupid of me not to try)

I've changed the code a bit so the output will always be consistent (I have changed my pull request too).
Right now when I try it and go to http://localhost:3000/stats/pc/us/Alf-1608?include=stats,combat,quickplay
it gives me this output:

`{"stats":{"combat":{"quickplay":[{"title":"Melee Final Blows","value":"115"},{"title":"Solo Kills","value":"3,452"},{"title":"Objective Kills","value":"11,565"},{"title":"Final Blows","value":"13,677"},{"title":"All Damage Done","value":"12,819,485"},{"title":"Eliminations","value":"29,376"},{"title":"Environmental Kills","value":"121"},{"title":"Multikills","value":"241"}]}}}`

Which is pretty much exactly what I was looking for :)

**Comment by alfg** [comment]
Ah, perfect! Thank you so much!

**Comment by Ruben-Smit** [comment]
You're welcome! I'm glad I could help.

**Pull request merged**
